pragma Singleton
import QtQuick
import Orme

// Orme - Copyright (c) 2026 Angelo Scarnà
// SPDX-License-Identifier: GPL-3.0-or-later
// Elenco dei 29 giochi, usato dal menu (Launcher) e dalla pagina Info.
// Campi: id, title, age, c (colore), e (emoji) o icon ("path"), desc.
QtObject {
    readonly property var games: [
        { cat: "infanzia", id: "path", title: qsTr("Il percorso"), age: qsTr("3-5 anni"), c: Theme.dirUp, icon: "path",
          desc: qsTr("Componi la fila di frecce; il robot le esegue un passo alla volta fino all'oggetto. Sequenza / algoritmo, e correggere e riprovare.") },
        { cat: "infanzia", id: "loop", title: qsTr("Ancora!"), age: qsTr("4-5 anni"), c: Theme.dirDown, e: "🐸",
          desc: qsTr("Scegli quante volte ripetere il salto: il coniglio deve arrivare esatto sulla carota. Il ciclo / ripetizione.") },
        { cat: "infanzia", id: "rhythm", title: qsTr("Il ritmo"), age: qsTr("3-5 anni"), c: Theme.dirRight, e: "🔴🔵",
          desc: qsTr("Una fila di pallini colorati che segue un ritmo e finisce con '?'. Tocca quello che continua il ritmo. I pattern.") },
        { cat: "infanzia", id: "sort", title: qsTr("Metti a posto"), age: qsTr("3-4 anni"), c: Theme.dirLeft, e: "📦",
          desc: qsTr("Trascina l'oggetto nel cesto giusto: per colore, per grandezza, per tipo. Classificare / condizione 'se... allora...'.") },
        { cat: "infanzia", id: "sequence", title: qsTr("E poi?"), age: qsTr("4-5 anni"), c: Theme.accent, e: "👣",
          desc: qsTr("Figure mescolate in alto, caselle 1-2-3 in basso: tocca le figure nell'ordine giusto (seme, germoglio, albero...).") },
        { cat: "infanzia", id: "draw", title: qsTr("Disegna il percorso"), age: qsTr("3-5 anni"), c: Theme.dirRight, e: "✏️",
          desc: qsTr("Col dito disegni una strada dal personaggio fino all'oggetto (fiore, pupazzo, palla...); poi lui la percorre.") },
        { cat: "infanzia", id: "catch", title: qsTr("Acchiappa i conigli"), age: qsTr("3-5 anni"), c: Theme.dirDown, e: "🐰",
          desc: qsTr("Fra gli animali che ondeggiano tocca solo i conigli. Toccare un altro animale è un errore.") },
        { cat: "infanzia", id: "count", title: qsTr("Conta"), age: qsTr("4-5 anni"), c: Theme.dirUp, e: "🔢",
          desc: qsTr("Quanti animali ci sono? Tocca il numero giusto, da 1 a 5.") },
        { cat: "infanzia", id: "color", title: qsTr("Tocca il colore"), age: qsTr("3-4 anni"), c: Theme.dirLeft, e: "🎨",
          desc: qsTr("In alto una macchia di colore, sotto quattro cerchi: tocca quello dello stesso colore.") },
        { cat: "infanzia", id: "odd", title: qsTr("Trova l'intruso"), age: qsTr("3-5 anni"), c: Theme.accent, e: "🔍",
          desc: qsTr("Quattro figure, tre uguali e una diversa: tocca quella diversa. Il confronto.") },
        { cat: "infanzia", id: "pairs", title: qsTr("Le coppie"), age: qsTr("4-5 anni"), c: Theme.dirUp, e: "🃏",
          desc: qsTr("Memory con 6 carte (3 coppie): giri due carte, se sono uguali restano su.") },
        { cat: "infanzia", id: "size", title: qsTr("Il più grande"), age: qsTr("3-4 anni"), c: Theme.dirDown, e: "🐘",
          desc: qsTr("Due o tre figure uguali di misura diversa: tocca la più grande.") },
        { cat: "infanzia", id: "bubbles", title: qsTr("Bolle"), age: qsTr("3-5 anni"), c: Theme.dirRight, e: "🔵",
          desc: qsTr("Le bolle colorate salgono piano: toccale per farle scoppiare. Toccane abbastanza per vincere.") },
        { cat: "infanzia", id: "dots", title: qsTr("Unisci i puntini"), age: qsTr("4-5 anni"), c: Theme.dirLeft, e: "⭐",
          desc: qsTr("Tocca i puntini in ordine da 1 a 5: a ogni tocco giusto si disegna un pezzo di linea.") },
        { cat: "infanzia", id: "wake", title: qsTr("Sveglia gli animali"), age: qsTr("3-4 anni"), c: Theme.accent, e: "😴",
          desc: qsTr("Sei animali dormono: toccali tutti per svegliarli, ognuno fa un saltino.") },
        { cat: "infanzia", id: "cups", title: qsTr("Dov'è il coniglio?"), age: qsTr("4-5 anni"), c: Theme.dirUp, e: "❓",
          desc: qsTr("Il coniglio si nasconde sotto un bicchiere; i bicchieri si mescolano, poi tocca quello giusto.") },
        { cat: "infanzia", id: "puzzle", title: qsTr("Puzzle"), age: qsTr("3-5 anni"), c: Theme.dirDown, e: "🧩",
          desc: qsTr("Quattro pezzi da trascinare nella cornice 2x2; ogni casella mostra in trasparenza il pezzo che ci va.") },
        { cat: "infanzia", id: "harvest", title: qsTr("Raccogli i frutti"), age: qsTr("3-5 anni"), c: Theme.dirRight, e: "🍎",
          desc: qsTr("I frutti colorati scendono piano dall'alto: toccali per metterli nel cesto.") },
        { cat: "infanzia", id: "balloons", title: qsTr("Palloncini in fila"), age: qsTr("3-5 anni"), c: Theme.dirLeft, e: "🎈",
          desc: qsTr("Tocca i palloncini dal più piccolo al più grande. Mettere in ordine per grandezza.") },
        { cat: "infanzia", id: "reveal", title: qsTr("Scopri chi è"), age: qsTr("3-4 anni"), c: Theme.accent, e: "🐱",
          desc: qsTr("Dietro le mattonelle colorate c'è un animale: toccale tutte per scoprirlo.") },
        { cat: "infanzia", id: "emotions", title: qsTr("Le emozioni"), age: qsTr("3-4 anni"), c: Theme.dirDown, e: "😀",
          desc: qsTr("In alto una faccia con un'emozione, sotto quattro facce diverse: tocca quella con la stessa emozione.") },
        { cat: "infanzia", id: "recycle", title: qsTr("La raccolta differenziata"), age: qsTr("3-5 anni"), c: Theme.dirRight, e: "♻️",
          desc: qsTr("Trascina l'oggetto nel bidone giusto: plastica, carta o vetro.") },
        { cat: "infanzia", id: "shapes", title: qsTr("Il percorso delle forme"), age: qsTr("3-5 anni"), c: Theme.dirLeft, e: "🔺",
          desc: qsTr("Sagome colorate sul pavimento in 5 file: in alto una forma o un colore indica la regola, tocca solo quelle giuste per attraversare l'aula.") },
        { cat: "infanzia", id: "snake", title: qsTr("Il serpente"), age: qsTr("4-5 anni"), c: Theme.accent, e: "🐍",
          desc: qsTr("Muovi il serpente con le frecce, una casella alla volta: mangia le mele e cresci, senza toccare i muri o il tuo stesso corpo.") },
        { cat: "infanzia", id: "stopgo", title: qsTr("Un, due, tre, stella!"), age: qsTr("3-4 anni"), c: Theme.danger, e: "🚦",
          desc: qsTr("Il semaforo cambia da solo: tocca 'cammina' per avanzare verso la stella solo col verde. Il controllo del corpo e lo stop.") },
        { cat: "infanzia", id: "poses", title: qsTr("Il gioco delle posizioni"), age: qsTr("3-4 anni"), c: Theme.dirUp, e: "🤸",
          desc: qsTr("In alto una posa (animale o supereroe): tocca fra le scelte quella uguale. Eseguire il comando indicato.") },
        { cat: "infanzia", id: "kitchen", title: qsTr("Cuciniamo insieme"), age: qsTr("3-4 anni"), c: Theme.dirLeft, e: "🍳",
          desc: qsTr("Gioco di ruolo in cucina: tocca gli oggetti nell'ordine giusto per completare l'azione. La sequenza dei passi.") },
        { cat: "infanzia", id: "tower", title: qsTr("Costruisci la torre"), age: qsTr("3-4 anni"), c: Theme.dirRight, e: "🧱",
          desc: qsTr("Trascina i blocchi colorati dal vassoio nella torre, dal basso verso l'alto, seguendo il modellino. Spazio e pazienza.") },
        { cat: "infanzia", id: "beans", title: qsTr("Travasi e infilo"), age: qsTr("3-4 anni"), c: Theme.accent, e: "🧃",
          desc: qsTr("Trascina la bottiglia sopra il bicchiere vuoto e tienila li': il liquido si travasa piano piano (acqua, succo, limonata...). La coordinazione occhio-mano.") },

        // --- Primaria ---
        { cat: "primaria", id: "add", title: qsTr("Addizioni"), age: qsTr("6-7 anni"), c: Theme.dirUp, e: "➕",
          desc: qsTr("Risolvi le addizioni con il tastierino numerico. Un problema alla volta, con stelle per ogni livello superato.") },
        { cat: "primaria", id: "sub", title: qsTr("Sottrazioni"), age: qsTr("6-7 anni"), c: Theme.dirDown, e: "➖",
          desc: qsTr("Risolvi le sottrazioni con il tastierino numerico. Un problema alla volta, con stelle per ogni livello superato.") },
        { cat: "primaria", id: "mul", title: qsTr("Moltiplicazioni"), age: qsTr("8-9 anni"), c: Theme.dirRight, e: "✖️",
          desc: qsTr("Risolvi le moltiplicazioni con il tastierino numerico. Un problema alla volta, con stelle per ogni livello superato.") },
        { cat: "primaria", id: "div", title: qsTr("Divisioni"), age: qsTr("8-9 anni"), c: Theme.dirLeft, e: "➗",
          desc: qsTr("Risolvi le divisioni, anche con il resto, con il tastierino numerico. Un problema alla volta, con stelle per ogni livello superato.") },
        { cat: "primaria", id: "fractions", title: qsTr("Frazioni"), age: qsTr("9-10 anni"), c: Theme.accent, e: "🍕",
          desc: qsTr("Frazioni di numeri interi, decimali e frazioni di un numero: scrivi il risultato giusto con il tastierino.") },
        { cat: "primaria", id: "tables", title: qsTr("Tabelline"), age: qsTr("8-9 anni"), c: Theme.dirUp, e: "🐟",
          desc: qsTr("Scegli la tabellina (dal 2 al 10) e tocca i pesci con i multipli in ordine crescente: ogni pesce pescato vola nella conchiglia. Attento alle vite!") },
        { cat: "primaria", id: "numberline", title: qsTr("La linea dei numeri"), age: qsTr("6-8 anni"), c: Theme.dirDown, e: "📏",
          desc: qsTr("Scegli la lunghezza della linea e la modalità (conta, addizione o sottrazione) e posiziona il segnalino sul numero giusto.") },
        { cat: "primaria", id: "regions", title: qsTr("Regioni d'Italia"), age: qsTr("8-10 anni"), c: Theme.accent, e: "🗺️",
          desc: qsTr("Quiz a 4 risposte su regioni e capoluoghi d'Italia: a volte si cerca il capoluogo, a volte la regione.") },
        { cat: "primaria", id: "syllables", title: qsTr("Sillabe"), age: qsTr("6-7 anni"), c: Theme.dirRight, e: "🔤",
          desc: qsTr("Le sillabe di una parola sono mescolate: toccale nell'ordine giusto per ricomporla.") },
        { cat: "primaria", id: "doubles", title: qsTr("Le doppie"), age: qsTr("7-8 anni"), c: Theme.dirUp, e: "✌️",
          desc: qsTr("Una frase con uno spazio vuoto e due parole quasi uguali: tocca quella scritta giusta.") },
        { cat: "primaria", id: "spelling", title: qsTr("Ortografia"), age: qsTr("7-9 anni"), c: Theme.dirLeft, e: "✏️",
          desc: qsTr("I trabocchetti dell'italiano: a/ha, e/è, o/ho, qu/cu... tocca la parola scritta giusta.") },
        { cat: "primaria", id: "lettercount", title: qsTr("Conta le lettere"), age: qsTr("6-7 anni"), c: Theme.dirDown, e: "🔡",
          desc: qsTr("Guarda la parola e scrivi con il tastierino quante lettere ha.") },
        { cat: "primaria", id: "guessword", title: qsTr("Indovina la parola"), age: qsTr("6-8 anni"), c: Theme.accent, e: "❓",
          desc: qsTr("Leggi l'indovinello e tocca la parola giusta fra quattro.") },
        { cat: "primaria", id: "reorder", title: qsTr("Riordina la frase"), age: qsTr("7-9 anni"), c: Theme.dirRight, e: "🔀",
          desc: qsTr("Le parole di una frase sono mescolate: toccale nell'ordine giusto per ricomporla.") },
        { cat: "primaria", id: "subjectverb", title: qsTr("Soggetto e predicato"), age: qsTr("8-9 anni"), c: Theme.dirUp, e: "📖",
          desc: qsTr("Una frase divisa in due pezzi: a volte tocca il soggetto, a volte il predicato.") },
        { cat: "primaria", id: "pronouns", title: qsTr("Pronomi"), age: qsTr("9-10 anni"), c: Theme.dirLeft, e: "💬",
          desc: qsTr("Scegli il tipo (personali, possessivi, dimostrativi, indefiniti, relativi) e completa la frase col pronome giusto.") }
    ]
}
